server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
        ephemeral: true #是否临时注册到nacos上,false表示持久化注册
    gateway:
      httpclient:
        # 网关全局连接超时时间(默认:45,单位:s)(动态生效)
        connect-timeout: 60
        # 网关全局响应超时时间(单位:ms或s,如5000或5s,metadata元数据配置中必须用ms单位)(动态生效)
        response-timeout: 600000
      #路由转发配置
      routes:
        - id: payment_routh                   #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:9001         #匹配后提供服务的路由地址
          uri: lb://nacos-payment-provider    #匹配后提供服务的路由地址, lb代表启用负载均衡功能，nacos-payment-provider表示nacos注册中的服务名
          predicates:
            - Path=/payment/nacos/**          # 断言，路径相匹配的进行路由
            #- After=2023-10-08T11:17:00.434859+08:00[Asia/Shanghai]    #断言：表示在这个时间之后可以访问
            #- Before=2023-10-08T11:21:00.434859+08:00[Asia/Shanghai]    #断言：Before就是设置的时间之前可以访问，过了时间之后不可以访问
            #- Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver]  #两个时间的区间是可以访问的，过了时间之后不可以访问



# yaml语法规范:
# 1.大小写敏感,优先级大于properties(后加载,同配置被properties覆盖)
# 2.通过缩进表示层级关系,禁止使用tab缩进,只能使用空格键
# 3.缩进的空格数目不重要,只要相同层级左对齐即可
# 4.使用#表示注释
# routes路由转发配置说明:
# id:路由编号,自定义且不可重复
# uri:可以是网址,也可以是服务,转发服务默认使用lb://serviceId(注册中心上的服务id)
# lb代表load balance负载均衡,可以转发负载均衡的Websocket请求lb:ws://serviceId
# predicates: Paths 路径谓词器,代表请求时转发的路径,多个用逗号分隔,这里用了自定义谓词Paths
# metadata元数据配置,可以用来设置路由级别超时,数据类型为整型