server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址
    gateway:
      routes:
        -id: payment_routh        #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
        uri: www.baidu.com       #匹配后提供服务的路由地址
        #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
        predicates:
          - Path=/payment/nacos/**         # 断言，路径相匹配的进行路由